apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive-default
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.24.0
    controller.receive.thanos.io/hashring: default
  name: thanos-receive-default
spec:
  #clusterIP: None
  type: LoadBalancer
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  - name: remote-write
    port: 9091
    targetPort: 19291
  selector:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive-default
    app.kubernetes.io/name: thanos-receive
    controller.receive.thanos.io/hashring: default